spring.application.name=JobTrack_Project

server.port = 8080
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = 2996sir


spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql= true


